import { z } from "zod";

import {
  booleanSchema,
  fontNameSchema,
  idParamsSchema,
  idSchema,
  integerIndexSchema,
  jsonArraySchema,
  jsonObjectSchema,
  maxBytesSchema,
  nodeTypeSchema,
  nonEmptyStringSchema,
  nonNegativeNumberSchema,
  numberSchema,
  pageOrNodeIdParamsSchema,
  paginatedPageOrNodeIdParamsSchema,
  rangeFields,
  rgbaSchema,
  schema,
  stringSchema,
  transformSchema,
} from "./schema.js";
import {
  operation as op,
  type NodeOperationDefinition,
} from "./strategy.js";

export const nodeOperationDefinitions: readonly NodeOperationDefinition[] = [
  op("node.setName", schema({ name: nonEmptyStringSchema })),
  op("node.remove", idParamsSchema),
  op("node.clone", idParamsSchema),
  op("node.getPluginData", schema({ key: nonEmptyStringSchema }), true),
  op("node.setPluginData", schema({ key: nonEmptyStringSchema, value: stringSchema })),
  op("node.getPluginDataKeys", idParamsSchema, true),
  op("node.removePluginData", schema({ key: nonEmptyStringSchema })),
  op("node.clearPluginData", idParamsSchema),
  op(
    "node.getSharedPluginData",
    schema({ namespace: nonEmptyStringSchema, key: nonEmptyStringSchema }),
    true,
  ),
  op(
    "node.setSharedPluginData",
    schema({
      namespace: nonEmptyStringSchema,
      key: nonEmptyStringSchema,
      value: stringSchema,
    }),
  ),
  op("node.getSharedPluginDataKeys", schema({ namespace: nonEmptyStringSchema }), true),
  op(
    "node.removeSharedPluginData",
    schema({ namespace: nonEmptyStringSchema, key: nonEmptyStringSchema }),
  ),
  op("node.clearSharedPluginData", schema({ namespace: nonEmptyStringSchema })),
  op("node.setVisible", schema({ isVisible: booleanSchema })),
  op("node.setLocked", schema({ isLocked: booleanSchema })),
  op("node.setComponentPropertyReferences", schema({ references: jsonObjectSchema.nullable() })),
  op("node.appendChild", schema({ childId: idSchema })),
  op("node.insertChild", schema({ index: integerIndexSchema, childId: idSchema })),
  op("node.findChildren", paginatedPageOrNodeIdParamsSchema, true),
  op("node.findAll", paginatedPageOrNodeIdParamsSchema, true),
  op(
    "node.findAllWithCriteria",
    schema({
      types: z.array(nodeTypeSchema).min(1).describe("Node types to match."),
      limit: z
        .number()
        .int()
        .min(1)
        .max(1000)
        .nullish()
        .describe("Maximum number of nodes to return. Defaults to 200."),
      offset: z
        .number()
        .int()
        .min(0)
        .nullish()
        .describe("Number of matching nodes to skip. Defaults to 0."),
    }),
    true,
  ),
  op("node.setPosition", schema({ x: numberSchema, y: numberSchema })),
  op("node.setSize", schema({ width: nonNegativeNumberSchema, height: nonNegativeNumberSchema })),
  op(
    "node.setBound",
    schema({
      bound: z
        .object({
          x: numberSchema,
          y: numberSchema,
          width: nonNegativeNumberSchema,
          height: nonNegativeNumberSchema,
        })
        .strict(),
    }),
  ),
  op(
    "node.setMinMaxSize",
    schema({
      minWidth: nonNegativeNumberSchema.nullish(),
      maxWidth: nonNegativeNumberSchema.nullish(),
      minHeight: nonNegativeNumberSchema.nullish(),
      maxHeight: nonNegativeNumberSchema.nullish(),
    }),
  ),
  op("node.setRotation", schema({ rotation: numberSchema })),
  op("node.setConstrainProportions", schema({ constrainProportions: booleanSchema })),
  op("node.setLayoutPositioning", schema({ layoutPositioning: z.enum(["AUTO", "ABSOLUTE"]) })),
  op("node.setAlignSelf", schema({ alignSelf: z.enum(["STRETCH", "INHERIT"]) })),
  op("node.setFlexGrow", schema({ flexGrow: z.union([z.literal(0), z.literal(1)]) })),
  op(
    "node.rescale",
    schema({
      scale: nonNegativeNumberSchema,
      scaleOption: jsonObjectSchema.nullish(),
    }),
  ),
  op("node.resize", schema({ width: nonNegativeNumberSchema, height: nonNegativeNumberSchema })),
  op("node.flip", schema({ direction: z.enum(["VERTICAL", "HORIZONTAL"]) })),
  op("node.setScaleFactor", schema({ scaleFactor: nonNegativeNumberSchema })),
  op("node.setAbsoluteTransform", schema({ absoluteTransform: transformSchema })),
  op("node.setRelativeTransform", schema({ relativeTransform: transformSchema })),
  op(
    "node.setConstraints",
    schema({
      constraints: z
        .object({
          horizontal: z.enum(["START", "END", "STARTANDEND", "CENTER", "SCALE"]),
          vertical: z.enum(["START", "END", "STARTANDEND", "CENTER", "SCALE"]),
        })
        .strict(),
    }),
  ),
  op("node.setOpacity", schema({ opacity: z.number().min(0).max(1) })),
  op(
    "node.setBlendMode",
    schema({
      blendMode: z.enum([
        "NORMAL",
        "DARKEN",
        "MULTIPLY",
        "COLOR_BURN",
        "LIGHTEN",
        "SCREEN",
        "COLOR_DODGE",
        "OVERLAY",
        "SOFT_LIGHT",
        "HARD_LIGHT",
        "DIFFERENCE",
        "EXCLUSION",
        "HUE",
        "SATURATION",
        "COLOR",
        "LUMINOSITY",
        "PLUS_DARKER",
        "PLUS_LIGHTER",
        "PASS_THROUGH",
      ]),
    }),
  ),
  op("node.setMask", schema({ isMask: booleanSchema })),
  op("node.setMaskOutline", schema({ isMaskOutline: booleanSchema })),
  op("node.setMaskVisible", schema({ isMaskVisible: booleanSchema })),
  op("node.setEffects", schema({ effects: jsonArraySchema })),
  op("node.setEffectStyleId", schema({ effectStyleId: stringSchema })),
  op("node.setFills", schema({ fills: jsonArraySchema })),
  op("node.setStrokes", schema({ strokes: jsonArraySchema })),
  op("node.setStrokeWeight", schema({ strokeWeight: nonNegativeNumberSchema })),
  op("node.setStrokeAlign", schema({ strokeAlign: z.enum(["CENTER", "INSIDE", "OUTSIDE"]) })),
  op(
    "node.setStrokeCap",
    schema({
      strokeCap: z.enum([
        "NONE",
        "ROUND",
        "SQUARE",
        "LINE_ARROW",
        "TRIANGLE_ARROW",
        "ROUND_ARROW",
        "RING",
        "DIAMOND",
        "LINE",
      ]),
    }),
  ),
  op("node.setStrokeJoin", schema({ strokeJoin: z.enum(["MITER", "BEVEL", "ROUND"]) })),
  op("node.setStrokeStyle", schema({ strokeStyle: z.enum(["SOLID", "DASH", "CUSTOM"]) })),
  op("node.setDashCap", schema({ dashCap: z.enum(["NONE", "ROUND", "SQUARE"]) })),
  op("node.setStrokeDashes", schema({ strokeDashes: z.array(nonNegativeNumberSchema) })),
  op("node.setFillStyleId", schema({ fillStyleId: stringSchema })),
  op("node.setStrokeStyleId", schema({ strokeStyleId: stringSchema })),
  op("node.setStrokeFillStyleId", schema({ strokeFillStyleId: stringSchema })),
  op("node.setStrokeWidthStyleId", schema({ strokeWidthStyleId: stringSchema })),
  op("node.setPaddingStyleId", schema({ paddingStyleId: stringSchema })),
  op("node.setSpacingStyleId", schema({ spacingStyleId: stringSchema })),
  op("node.setCornerRadiusStyleId", schema({ cornerRadiusStyleId: stringSchema })),
  op("node.outlineStroke", idParamsSchema),
  op("node.setCornerSmooth", schema({ cornerSmooth: nonNegativeNumberSchema })),
  op("node.setCornerRadius", schema({ cornerRadius: nonNegativeNumberSchema })),
  op(
    "node.setIndependentCornerRadii",
    schema({
      topLeftRadius: nonNegativeNumberSchema,
      topRightRadius: nonNegativeNumberSchema,
      bottomLeftRadius: nonNegativeNumberSchema,
      bottomRightRadius: nonNegativeNumberSchema,
    }),
  ),
  op(
    "node.setRectangleStrokeWeights",
    schema({
      strokeTopWeight: nonNegativeNumberSchema,
      strokeLeftWeight: nonNegativeNumberSchema,
      strokeBottomWeight: nonNegativeNumberSchema,
      strokeRightWeight: nonNegativeNumberSchema,
    }),
  ),
  op("node.setExpanded", schema({ expanded: booleanSchema })),
  op("node.setAutoLayout", schema({ autoLayout: jsonObjectSchema })),
  op("node.setClipsContent", schema({ clipsContent: booleanSchema })),
  op("node.setLayoutGrids", schema({ layoutGrids: jsonArraySchema })),
  op("node.setGridStyleId", schema({ gridStyleId: stringSchema })),
  op("node.setOverflowDirection", schema({ overflowDirection: z.enum(["NONE", "HORIZONTAL", "VERTICAL", "BOTH"]) })),
  op("node.resizeToFit", idParamsSchema),
  op("node.setExportSettings", schema({ exportSettings: jsonArraySchema })),
  op("node.export", schema({ settings: jsonObjectSchema.nullish(), maxBytes: maxBytesSchema }), true),
  op("node.exportAsync", schema({ settings: jsonObjectSchema.nullish(), maxBytes: maxBytesSchema }), true),
  op("node.exportPng", schema({ settings: jsonObjectSchema.nullish() }), true),
  op("node.page.setSelection", schema({ selectionIds: z.array(idSchema) })),
  op("node.page.selectAll", pageOrNodeIdParamsSchema),
  op("node.page.setBgColor", schema({ bgColor: rgbaSchema })),
  op(
    "node.page.setLabel",
    schema({ label: z.enum(["NONE", "BLUE", "GREEN", "RED", "YELLOW", "PURPLE", "GRAY"]) }),
  ),
  op("node.page.clone", pageOrNodeIdParamsSchema),
  op("node.ellipse.setArcData", schema({ arcData: jsonObjectSchema })),
  op("node.polygon.setPointCount", schema({ pointCount: z.number().int().min(3) })),
  op("node.star.setPointCount", schema({ pointCount: z.number().int().min(3) })),
  op("node.star.setInnerRadius", schema({ innerRadius: nonNegativeNumberSchema })),
  op("node.pen.setPenPaths", schema({ penPaths: jsonArraySchema })),
  op("node.boolean.setOperation", schema({ booleanOperation: z.enum(["UNION", "INTERSECT", "SUBTRACT", "EXCLUDE"]) })),
  op("node.line.setCaps", schema({ leftStrokeCap: stringSchema, rightStrokeCap: stringSchema })),
  op("node.intelligentContainer.setShaderCode", schema({ shaderCode: stringSchema })),
  op("node.intelligentContainer.setPlaying", schema({ isPlaying: booleanSchema })),
  op("node.slice.setPreserveRatio", schema({ isPreserveRatio: booleanSchema })),
  op("node.connector.createText", idParamsSchema),
  op("node.connector.getText", idParamsSchema, true),
  op("node.connector.setCornerRadius", schema({ cornerRadius: nonNegativeNumberSchema.nullish() })),
  op("node.connector.setEndpoints", schema({ connectorStart: jsonObjectSchema, connectorEnd: jsonObjectSchema })),
  op("node.connector.setStrokeCaps", schema({ connectorStartStrokeCap: stringSchema, connectorEndStrokeCap: stringSchema })),
  op("node.text.setCharacters", schema({ characters: stringSchema })),
  op("node.text.insertCharacters", schema({ start: integerIndexSchema, characters: stringSchema })),
  op("node.text.deleteCharacters", schema({ start: integerIndexSchema, end: integerIndexSchema })),
  op("node.text.setAlignHorizontal", schema({ textAlignHorizontal: z.enum(["LEFT", "CENTER", "RIGHT", "JUSTIFIED"]) })),
  op("node.text.setAlignVertical", schema({ textAlignVertical: z.enum(["TOP", "CENTER", "BOTTOM"]) })),
  op(
    "node.text.setAutoResize",
    schema({
      textAutoResize: z.enum([
        "NONE",
        "WIDTH_AND_HEIGHT",
        "HEIGHT",
        "TRUNCATE",
        "TRUNCATE_AND_AUTO_WIDTH",
        "TRUNCATE_AND_AUTO_HEIGHT",
      ]),
    }),
  ),
  op("node.text.setParagraphSpacing", schema({ paragraphSpacing: nonNegativeNumberSchema })),
  op(
    "node.text.setRangeFontSize",
    schema({ ...rangeFields, fontSize: nonNegativeNumberSchema.describe("Font size in pixels.") }),
  ),
  op(
    "node.text.setRangeTextDecoration",
    schema({ ...rangeFields, decoration: z.enum(["NONE", "UNDERLINE", "STRIKETHROUGH"]) }),
  ),
  op("node.text.setRangeFontName", schema({ ...rangeFields, fontName: fontNameSchema })),
  op("node.text.setRangeLetterSpacing", schema({ ...rangeFields, letterSpacing: jsonObjectSchema })),
  op("node.text.setRangeLineHeight", schema({ ...rangeFields, lineHeight: jsonObjectSchema })),
  op("node.text.setRangeFills", schema({ ...rangeFields, fills: jsonArraySchema })),
  op("node.text.setRangeHyperlink", schema({ ...rangeFields, hyperlink: jsonObjectSchema.nullish() })),
  op("node.text.setRangeTextCase", schema({ ...rangeFields, textCase: z.enum(["ORIGINAL", "UPPER", "LOWER", "TITLE"]) })),
  op("node.text.setRangeListStyle", schema({ ...rangeFields, listStyle: z.enum(["ORDERED", "BULLETED", "NONE"]) })),
  op("node.text.setRangeFillStyleId", schema({ ...rangeFields, fillStyleId: stringSchema })),
  op("node.text.setRangeTextStyleId", schema({ ...rangeFields, textStyleId: stringSchema })),
  op(
    "node.component.addProperty",
    schema({
      propertyName: nonEmptyStringSchema,
      type: z.enum(["BOOLEAN", "TEXT", "INSTANCE_SWAP"]),
      defaultValue: z.union([stringSchema, booleanSchema]),
      options: jsonObjectSchema.nullish(),
    }),
  ),
  op("node.component.editProperty", schema({ propertyId: nonEmptyStringSchema, newValue: jsonObjectSchema })),
  op("node.component.deleteProperty", schema({ propertyId: nonEmptyStringSchema })),
  op("node.component.setVariantPropertyValues", schema({ properties: z.record(z.string(), stringSchema) })),
  op("node.component.createInstance", idParamsSchema),
  op("node.componentSet.createVariantComponent", idParamsSchema),
  op("node.componentSet.createVariantProperties", schema({ properties: z.array(nonEmptyStringSchema) })),
  op("node.componentSet.editVariantProperties", schema({ properties: z.record(z.string(), stringSchema) })),
  op("node.componentSet.editVariantPropertyValues", schema({ properties: jsonObjectSchema })),
  op("node.componentSet.editVariantPropertiesAlias", schema({ properties: z.record(z.string(), stringSchema) })),
  op("node.componentSet.editVariantPropertyValuesAlias", schema({ properties: jsonObjectSchema })),
  op("node.componentSet.deleteVariantProperty", schema({ property: nonEmptyStringSchema })),
  op("node.instance.setVariantPropertyValues", schema({ properties: z.record(z.string(), stringSchema) })),
  op("node.instance.setProperties", schema({ properties: z.record(z.string(), z.union([stringSchema, booleanSchema])) })),
  op("node.instance.setExposedInstance", schema({ isExposedInstance: booleanSchema })),
  op("node.instance.resetOverrides", idParamsSchema),
  op("node.instance.swapComponent", schema({ componentId: idSchema })),
  op("node.instance.detach", idParamsSchema),
  op("node.instance.setMainComponent", schema({ componentId: idSchema.nullish() })),
];
