import type { NodeOperationDefinition } from "./strategy.js";

type OperationMetadata = Pick<
  NodeOperationDefinition,
  "title" | "description" | "resultDescription"
>;

export const nodeOperationMetadata: Record<string, OperationMetadata> = {
  "node.setName": write("Set node name", "Set a page or scene node name."),
  "node.remove": write("Remove node", "Remove a page or scene node from the document."),
  "node.clone": write("Clone node", "Clone a page or scene node and return the new node summary."),
  "node.getPluginData": read("Get plugin data", "Read one plugin data value from a scene node."),
  "node.setPluginData": write("Set plugin data", "Set one plugin data key/value pair on a scene node."),
  "node.getPluginDataKeys": read("List plugin data keys", "List plugin data keys stored on a scene node."),
  "node.removePluginData": write("Remove plugin data", "Remove one plugin data key from a scene node."),
  "node.clearPluginData": write("Clear plugin data", "Remove all plugin data keys from a scene node."),
  "node.getSharedPluginData": read("Get shared plugin data", "Read one shared plugin data value from a scene node namespace."),
  "node.setSharedPluginData": write("Set shared plugin data", "Set one shared plugin data key/value pair on a scene node namespace."),
  "node.getSharedPluginDataKeys": read("List shared plugin data keys", "List shared plugin data keys in a scene node namespace."),
  "node.removeSharedPluginData": write("Remove shared plugin data", "Remove one shared plugin data key from a scene node namespace."),
  "node.clearSharedPluginData": write("Clear shared plugin data", "Remove all shared plugin data keys from a scene node namespace."),
  "node.setVisible": write("Set node visibility", "Set whether a scene node is visible."),
  "node.setLocked": write("Set node lock state", "Set whether a scene node is locked."),
  "node.setComponentPropertyReferences": write("Set component property references", "Replace component property references on a scene node."),
  "node.appendChild": write("Append child node", "Append a scene node as the last child of a page or container node."),
  "node.insertChild": write("Insert child node", "Insert a scene node into a page or container node at one index."),
  "node.findChildren": read("Find direct child nodes", "Find direct child scene nodes with pagination and return compact node summaries."),
  "node.findAll": read("Find descendant nodes", "Find descendant scene nodes with pagination and return compact node summaries."),
  "node.findAllWithCriteria": read("Find descendant nodes by type", "Find descendant scene nodes matching node types with pagination."),
  "node.setPosition": write("Set node position", "Set a scene node x and y coordinates."),
  "node.setSize": write("Set node size", "Set a scene node width and height."),
  "node.setBound": write("Set node bounds", "Set a scene node bound rectangle."),
  "node.setMinMaxSize": write("Set min and max size", "Set min/max width and height constraints on a scene node."),
  "node.setRotation": write("Set node rotation", "Set a scene node rotation in degrees."),
  "node.setConstrainProportions": write("Set proportional resizing", "Set whether a scene node constrains proportions while resizing."),
  "node.setLayoutPositioning": write("Set layout positioning", "Set a scene node layout positioning mode inside auto layout."),
  "node.setAlignSelf": write("Set align self", "Set a scene node alignSelf value inside auto layout."),
  "node.setFlexGrow": write("Set flex grow", "Set a scene node flexGrow value inside auto layout."),
  "node.rescale": write("Rescale node", "Rescale a scene node by a scale factor."),
  "node.resize": write("Resize node", "Resize a scene node using its resize method."),
  "node.flip": write("Flip node", "Flip a scene node vertically or horizontally."),
  "node.setScaleFactor": write("Set scale factor", "Set a scene node scaleFactor property."),
  "node.setAbsoluteTransform": write("Set absolute transform", "Set a scene node absolute transform matrix."),
  "node.setRelativeTransform": write("Set relative transform", "Set a scene node relative transform matrix."),
  "node.setConstraints": write("Set constraints", "Set a scene node horizontal and vertical constraints."),
  "node.setOpacity": write("Set opacity", "Set a scene node opacity from 0 to 1."),
  "node.setBlendMode": write("Set blend mode", "Set a scene node blend mode."),
  "node.setMask": write("Set mask flag", "Set whether a scene node is used as a mask."),
  "node.setMaskOutline": write("Set mask outline", "Set whether a scene node mask outline is enabled."),
  "node.setMaskVisible": write("Set mask visibility", "Set whether a scene node mask is visible."),
  "node.setEffects": write("Set effects", "Replace the node effects array."),
  "node.setEffectStyleId": write("Set effect style id", "Bind or clear an effect style id on a scene node."),
  "node.setFills": write("Set fills", "Replace the node fills array, commonly used to set solid, gradient, or image fills."),
  "node.setStrokes": write("Set strokes", "Replace the node strokes array."),
  "node.setStrokeWeight": write("Set stroke weight", "Set the node stroke weight."),
  "node.setStrokeAlign": write("Set stroke align", "Set the node stroke alignment."),
  "node.setStrokeCap": write("Set stroke cap", "Set the node stroke cap style."),
  "node.setStrokeJoin": write("Set stroke join", "Set the node stroke join style."),
  "node.setStrokeStyle": write("Set stroke style", "Set whether node strokes are solid, dashed, or custom."),
  "node.setDashCap": write("Set dash cap", "Set the node dash cap style."),
  "node.setStrokeDashes": write("Set stroke dashes", "Replace the node stroke dash pattern."),
  "node.setFillStyleId": write("Set fill style id", "Bind or clear a fill style id on a scene node."),
  "node.setStrokeStyleId": write("Set stroke style id", "Bind or clear the deprecated stroke style id on a scene node."),
  "node.setStrokeFillStyleId": write("Set stroke fill style id", "Bind or clear a stroke fill style id on a scene node."),
  "node.setStrokeWidthStyleId": write("Set stroke width style id", "Bind or clear a stroke width style id on a scene node."),
  "node.setPaddingStyleId": write("Set padding style id", "Bind or clear a padding style id on a scene node."),
  "node.setSpacingStyleId": write("Set spacing style id", "Bind or clear a spacing style id on a scene node."),
  "node.setCornerRadiusStyleId": write("Set corner radius style id", "Bind or clear a corner radius style id on a scene node."),
  "node.outlineStroke": write("Outline stroke", "Convert a stroked node outline into a scene node when supported."),
  "node.setCornerSmooth": write("Set corner smooth", "Set the node corner smoothing value."),
  "node.setCornerRadius": write("Set corner radius", "Set a uniform corner radius on a corner-capable node."),
  "node.setIndependentCornerRadii": write("Set independent corner radii", "Set top-left, top-right, bottom-left, and bottom-right radii."),
  "node.setRectangleStrokeWeights": write("Set rectangle stroke weights", "Set individual top, left, bottom, and right stroke weights."),
  "node.setExpanded": write("Set expanded state", "Set whether a container node is expanded."),
  "node.setAutoLayout": write("Set auto layout", "Set auto-layout related properties on a frame or container node."),
  "node.setClipsContent": write("Set clips content", "Set whether a frame or container clips overflowing content."),
  "node.setLayoutGrids": write("Set layout grids", "Replace layout grids on a frame or container node."),
  "node.setGridStyleId": write("Set grid style id", "Bind or clear a grid style id on a frame or container node."),
  "node.setOverflowDirection": write("Set overflow direction", "Set overflow direction on a frame or container node."),
  "node.resizeToFit": write("Resize to fit", "Resize a frame, component, or container to fit its children when supported."),
  "node.setExportSettings": write("Set export settings", "Replace export settings on an export-capable scene node."),
  "node.export": read("Export node", "Export a node synchronously and return a string or base64 encoded binary payload."),
  "node.exportAsync": read("Export node asynchronously", "Export a node asynchronously and return a string or base64 encoded binary payload."),
  "node.exportPng": read("Export node as PNG", "Export a node as a PNG data string using MasterGo exportPng."),
  "node.page.setSelection": write("Set page selection", "Set the current selection on a page by scene node ids."),
  "node.page.selectAll": write("Select all page nodes", "Select all scene nodes on a page."),
  "node.page.setBgColor": write("Set page background color", "Set a page background RGBA color."),
  "node.page.setLabel": write("Set page label", "Set a page label color."),
  "node.page.clone": write("Clone page", "Clone a page and return the new page summary."),
  "node.ellipse.setArcData": write("Set ellipse arc data", "Set arc data on an ellipse node."),
  "node.polygon.setPointCount": write("Set polygon point count", "Set the number of points on a polygon node."),
  "node.star.setPointCount": write("Set star point count", "Set the number of points on a star node."),
  "node.star.setInnerRadius": write("Set star inner radius", "Set the inner radius on a star node."),
  "node.pen.setPenPaths": write("Set pen paths", "Replace pen paths on a pen node."),
  "node.boolean.setOperation": write("Set boolean operation", "Set the boolean operation mode on a boolean operation node."),
  "node.line.setCaps": write("Set line caps", "Set left and right stroke caps on a line node."),
  "node.intelligentContainer.setShaderCode": write("Set shader code", "Set shader code on an intelligent container node."),
  "node.intelligentContainer.setPlaying": write("Set playback state", "Set whether an intelligent container is playing."),
  "node.slice.setPreserveRatio": write("Set preserve ratio", "Set whether a slice node preserves its aspect ratio."),
  "node.connector.createText": write("Create connector text", "Create a text sublayer on a connector node."),
  "node.connector.getText": read("Get connector text", "Return the connector text sublayer summary, or null."),
  "node.connector.setCornerRadius": write("Set connector corner radius", "Set the corner radius on a connector node."),
  "node.connector.setEndpoints": write("Set connector endpoints", "Set connector start and end endpoints."),
  "node.connector.setStrokeCaps": write("Set connector stroke caps", "Set connector start and end stroke cap styles."),
  "node.text.setCharacters": write("Set text characters", "Replace all characters on a TextNode or connector text sublayer."),
  "node.text.insertCharacters": write("Insert text characters", "Insert characters at an index on a TextNode or connector text sublayer."),
  "node.text.deleteCharacters": write("Delete text range", "Delete characters in a text range on a TextNode or connector text sublayer."),
  "node.text.setAlignHorizontal": write("Set horizontal text alignment", "Set horizontal alignment on a TextNode or connector text sublayer."),
  "node.text.setAlignVertical": write("Set vertical text alignment", "Set vertical alignment on a TextNode or connector text sublayer."),
  "node.text.setAutoResize": write("Set text auto resize", "Set text auto-resize behavior on a TextNode or connector text sublayer."),
  "node.text.setParagraphSpacing": write("Set paragraph spacing", "Set paragraph spacing on a TextNode or connector text sublayer."),
  "node.text.setRangeFontSize": write("Set range font size", "Set font size for a text range on a TextNode or connector text sublayer."),
  "node.text.setRangeTextDecoration": write("Set range text decoration", "Set underline, strikethrough, or no decoration for a text range."),
  "node.text.setRangeFontName": write("Set range font name", "Set font family and style for a text range."),
  "node.text.setRangeLetterSpacing": write("Set range letter spacing", "Set letter spacing for a text range."),
  "node.text.setRangeLineHeight": write("Set range line height", "Set line height for a text range."),
  "node.text.setRangeFills": write("Set range fills", "Set fill paints for a text range, commonly used to set text color."),
  "node.text.setRangeHyperlink": write("Set range hyperlink", "Set or clear a hyperlink for a text range."),
  "node.text.setRangeTextCase": write("Set range text case", "Set text case transformation for a text range."),
  "node.text.setRangeListStyle": write("Set range list style", "Set ordered, bulleted, or no list style for a text range."),
  "node.text.setRangeFillStyleId": write("Set range fill style id", "Bind or clear a fill style id for a text range."),
  "node.text.setRangeTextStyleId": write("Set range text style id", "Bind or clear a text style id for a text range."),
  "node.component.addProperty": write("Add component property", "Add a component property and return its property id."),
  "node.component.editProperty": write("Edit component property", "Edit a component property and return its property id."),
  "node.component.deleteProperty": write("Delete component property", "Delete a component property from a component or component set."),
  "node.component.setVariantPropertyValues": write("Set component variant values", "Set variant property values on a component node."),
  "node.component.createInstance": write("Create component instance", "Create an instance from a component node and return the new instance summary."),
  "node.componentSet.createVariantComponent": write("Create variant component", "Create a new variant component in a component set."),
  "node.componentSet.createVariantProperties": write("Create variant properties", "Create variant properties on a component set."),
  "node.componentSet.editVariantProperties": write("Edit variant properties", "Rename or edit variant properties on a component set."),
  "node.componentSet.editVariantPropertyValues": write("Edit variant property values", "Edit variant property values on a component set."),
  "node.componentSet.editVariantPropertiesAlias": write("Edit variant property aliases", "Edit aliases for variant properties on a component set."),
  "node.componentSet.editVariantPropertyValuesAlias": write("Edit variant value aliases", "Edit aliases for variant property values on a component set."),
  "node.componentSet.deleteVariantProperty": write("Delete variant property", "Delete one variant property from a component set."),
  "node.instance.setVariantPropertyValues": write("Set instance variant values", "Set variant property values on an instance node."),
  "node.instance.setProperties": write("Set instance properties", "Set component properties on an instance node."),
  "node.instance.setExposedInstance": write("Set exposed instance flag", "Set whether an instance is exposed."),
  "node.instance.resetOverrides": write("Reset instance overrides", "Reset overrides on an instance node."),
  "node.instance.swapComponent": write("Swap instance component", "Swap an instance to another component node."),
  "node.instance.detach": write("Detach instance", "Detach an instance into a frame and return the detached frame summary."),
  "node.instance.setMainComponent": write("Set main component", "Set or clear the main component of an instance node."),
};

function read(title: string, description: string): OperationMetadata {
  return {
    title,
    description,
    resultDescription: "Read operation result.",
  };
}

function write(title: string, description: string): OperationMetadata {
  return {
    title,
    description,
    resultDescription: "Updated compact node summary or operation result.",
  };
}
